export const conceptDescriptions: Record<string, string> = {
  // Mathematics
  'Fibonacci Sequence': 'A series where each number is the sum of the two preceding ones. Found throughout nature — in sunflower spirals, pine cones, and galaxy arms — it reveals a deep mathematical order underlying organic growth.',
  'Golden Ratio': 'The irrational number φ ≈ 1.618, found when a line is divided so the ratio of the whole to the larger part equals the ratio of the larger to the smaller. Revered since antiquity for its appearance in art, architecture, and nature.',
  'Infinite Series': 'The sum of infinitely many terms. Some converge to finite values (like 1 + ½ + ¼ + ⅛… = 2), others diverge to infinity. They are the foundation of calculus and our ability to approximate the continuous from the discrete.',
  'Topology': 'The study of properties preserved under continuous deformation — stretching, bending, but not tearing. A coffee mug and a donut are topologically identical. It reveals the deep structure of space itself.',
  'Prime Numbers': 'Numbers divisible only by 1 and themselves. The atoms of arithmetic — every integer is a unique product of primes. Their distribution remains one of mathematics\' deepest mysteries.',
  'Chaos Theory': 'The study of systems where tiny changes in initial conditions produce vastly different outcomes. The "butterfly effect." Deterministic yet unpredictable, it bridges order and randomness.',
  'Fractals': 'Geometric shapes that exhibit self-similarity at every scale. Zoom into a coastline, a fern, or the Mandelbrot set and you find the same patterns repeating infinitely. They measure the roughness of reality.',
  'Set Theory': 'The foundation of modern mathematics, studying collections of objects and their relationships. From it arise the concepts of infinity, cardinality, and the very language in which all mathematics is expressed.',
  'Number Theory': 'The "queen of mathematics" — the study of integers and their properties. From ancient Greek puzzles about perfect numbers to modern cryptography, it spans millennia of human curiosity.',
  'Geometry': 'The study of shape, size, and spatial relationships. From Euclid\'s axioms to Riemannian manifolds, geometry gives us the language to describe the fabric of space itself.',
  'Calculus': 'The mathematics of change and accumulation. Differentiation captures instantaneous rates; integration totals continuous quantities. It gave humanity the power to model the physical world.',
  'Statistics': 'The science of learning from data. It transforms uncertainty into knowledge, enabling us to find patterns, test hypotheses, and make decisions in the face of incomplete information.',
  'Probability': 'The mathematics of uncertainty. It quantifies likelihood, from coin flips to quantum mechanics, and underpins our understanding of risk, randomness, and the nature of information.',
  'Graph Theory': 'The study of networks — nodes connected by edges. From social networks to neural pathways to the internet, it reveals the hidden structure of connected systems.',
  'Abstract Algebra': 'The study of algebraic structures — groups, rings, fields — that generalize arithmetic. It reveals the deep symmetries underlying physics, chemistry, and geometry.',

  // Music
  'Harmonic Resonance': 'When frequencies align in simple ratios, they reinforce each other, producing the rich, full sound we perceive as harmony. It\'s the physics behind why certain notes sound beautiful together.',
  'Counterpoint': 'The art of combining independent melodic lines into a unified whole. Perfected by Bach, it represents one of humanity\'s most sophisticated intellectual achievements in organizing sound.',
  'Modulation': 'The process of changing from one key to another within a piece. It creates emotional journeys — tension, surprise, homecoming — and is the harmonic engine of musical narrative.',
  'Rhythm Patterns': 'The organization of sound in time. From the heartbeat to polyrhythmic African drumming to electronic beats, rhythm is the most primal and universal element of music.',
  'Melody Structure': 'The horizontal dimension of music — a sequence of pitches that forms a recognizable, singable line. Melody is how music speaks most directly to human emotion and memory.',
  'Timbre': 'The "color" of sound — what makes a violin sound different from a flute playing the same note. It arises from the complex mixture of overtones unique to each instrument and voice.',
  'Dynamics': 'The variation of loudness in music. From the whispered pianissimo to thundering fortissimo, dynamics give music its emotional intensity and dramatic arc.',
  'Consonance': 'The perception of stability and rest when certain intervals sound together. Rooted in the physics of simple frequency ratios, it\'s the anchor point from which all musical tension departs and returns.',
  'Dissonance': 'The perception of tension or instability in sound combinations. Far from being "wrong," dissonance is the engine of musical expression — it creates the desire for resolution that drives music forward.',
  'Musical Form': 'The large-scale architecture of a composition. Sonata, rondo, fugue, blues — these templates organize musical time into comprehensible narratives of departure and return.',
  'Improvisation': 'Real-time composition — the art of creating music in the moment. It demands deep knowledge internalized so completely that it becomes spontaneous expression, a dialogue between structure and freedom.',
  'Polyrhythm': 'The simultaneous use of contrasting rhythmic patterns. Found in West African drumming, Indian classical music, and modern jazz, it creates a rich, multidimensional temporal fabric.',
  'Modal Scales': 'Ancient scale systems — Dorian, Phrygian, Lydian — each with a distinct emotional color. They predate major/minor tonality and offer a vast palette of melodic and harmonic possibilities.',
  'Overtones': 'The hidden frequencies that vibrate above any fundamental tone. They determine timbre and create the harmonic series — nature\'s own chord, present in every musical sound.',
  'Syncopation': 'Emphasis on unexpected beats, creating rhythmic surprise and forward momentum. It\'s the swing in jazz, the groove in funk, the spark that makes music feel alive and unpredictable.',

  // Philosophy
  'Consciousness': 'The "hard problem" — why does subjective experience exist? Why is there something it is like to see red or feel pain? It remains the deepest unsolved question about the nature of mind.',
  'Free Will': 'Do we truly choose our actions, or are they determined by prior causes? This question sits at the intersection of physics, neuroscience, ethics, and our deepest intuitions about what it means to be human.',
  'Ethics': 'The philosophical study of right and wrong, good and evil. From Aristotle\'s virtue ethics to Kant\'s categorical imperative to utilitarian calculus, it asks: how should we live?',
  'Truth': 'What makes a statement true? Correspondence with reality? Internal coherence? Practical usefulness? The nature of truth is foundational to logic, science, and our ability to communicate meaning.',
  'Beauty': 'Is beauty in the object or the eye of the beholder? From Plato\'s Forms to Kant\'s aesthetics to neuroscience of perception, the nature of beauty connects art, mathematics, and human experience.',
  'Justice': 'What do we owe each other? From Rawls\' veil of ignorance to Nozick\'s libertarianism, theories of justice shape our institutions, laws, and vision of a fair society.',
  'Reality': 'What exists, and what is its fundamental nature? Are we in a simulation? Is matter fundamental, or consciousness? The question of reality underpins all other philosophical inquiry.',
  'Knowledge': 'What can we know, and how can we know it? From Plato\'s justified true belief to Gettier problems to Bayesian epistemology, the study of knowledge shapes science, education, and rational inquiry.',
  'Existence': 'Why is there something rather than nothing? The most fundamental question of metaphysics, it confronts us with the sheer mystery of being — that anything exists at all.',
  'Meaning': 'What gives life meaning? Is meaning discovered or created? From existentialism\'s radical freedom to religious frameworks to absurdism, this question drives our deepest personal and collective quests.',
  'Dialectics': 'The method of reasoning through contradiction — thesis, antithesis, synthesis. From Socratic dialogue to Hegel to Marx, dialectical thinking reveals truth through the collision of opposing ideas.',
  'Phenomenology': 'The study of experience as it is lived, before theoretical interpretation. Founded by Husserl, developed by Heidegger and Merleau-Ponty, it returns philosophy to the texture of direct experience.',
  'Ontology': 'The study of what exists and the categories of being. What kinds of things are real? Do numbers exist? Do possibilities? Ontology provides the inventory of reality.',
  'Epistemology': 'The theory of knowledge — its nature, sources, and limits. How do we distinguish genuine knowledge from mere belief? What role do perception, reason, and testimony play?',
  'Metaphysics': 'The study of the fundamental nature of reality — what exists beyond the physical. It asks about causation, time, identity, and the ultimate structure of everything that is.',

  // Physics
  'Quantum Entanglement': 'When two particles become entangled, measuring one instantly determines the state of the other, regardless of distance. Einstein called it "spooky action at a distance." It challenges our deepest intuitions about locality and reality.',
  'Wave-Particle Duality': 'Light and matter behave as both waves and particles, depending on how they\'re observed. This fundamental mystery of quantum mechanics reveals that reality at its smallest scale defies classical categories.',
  'Relativity': 'Einstein\'s twin revolutions: special relativity unites space and time; general relativity reveals gravity as the curvature of spacetime itself. They reshaped our understanding of the cosmos.',
  'Thermodynamics': 'The science of heat, energy, and entropy. Its laws govern everything from engines to black holes to the arrow of time itself. The second law — entropy always increases — may be the most universal law in physics.',
  'Electromagnetic Fields': 'Electric and magnetic fields are two aspects of a single force, unified by Maxwell\'s equations. This unification revealed that light is an electromagnetic wave and launched the modern technological era.',
  'String Theory': 'A theoretical framework proposing that fundamental particles are actually tiny vibrating strings. Different vibration patterns produce different particles. It promises to unify quantum mechanics and gravity.',
  'Dark Matter': 'An invisible substance that makes up ~27% of the universe. We know it exists from its gravitational effects on galaxies, but its nature remains one of physics\' greatest mysteries.',
  'Energy Conservation': 'Energy cannot be created or destroyed, only transformed. This principle, connected to time symmetry by Noether\'s theorem, is one of the deepest and most universal laws of nature.',
  'Momentum': 'The quantity of motion — mass times velocity. Its conservation in isolated systems reflects the fundamental symmetry of space itself: physics works the same everywhere.',
  'Gravity': 'The most familiar force, yet the most mysterious. Newton described it as attraction between masses; Einstein revealed it as the curvature of spacetime. Quantum gravity remains physics\' holy grail.',
  'Nuclear Forces': 'The strong force binds quarks into protons and neutrons, and holds atomic nuclei together. The weak force governs radioactive decay. Together, they shape the heart of matter.',
  'Particle Physics': 'The study of nature\'s smallest constituents. The Standard Model describes 17 fundamental particles and their interactions — quarks, leptons, bosons — painting a remarkably complete picture of reality\'s building blocks.',
  'Cosmology': 'The study of the universe\'s origin, structure, and fate. From the Big Bang to cosmic inflation to dark energy, cosmology addresses the grandest questions: where did everything come from, and where is it going?',
  'Fluid Dynamics': 'The physics of flowing substances — air, water, plasma. From weather patterns to blood flow to star formation, fluid dynamics reveals the beautiful complexity that emerges from simple physical laws.',
  'Optics': 'The study of light and its interactions with matter. From lenses and mirrors to fiber optics to quantum optics, understanding light has driven both fundamental physics and transformative technology.',

  // Art
  'Color Theory': 'The science and art of how colors interact, complement, and contrast. From Newton\'s color wheel to Albers\' interactions, it reveals how perception transforms wavelengths of light into emotional experience.',
  'Composition': 'The arrangement of visual elements within a frame. Rule of thirds, golden ratio, dynamic symmetry — composition guides the eye and creates meaning through spatial relationships.',
  'Perspective': 'The technique of representing three-dimensional space on a flat surface. Invented in the Renaissance, it revolutionized art and changed how humans understand their relationship to space.',
  'Light and Shadow': 'Chiaroscuro — the interplay of light and dark that creates depth, drama, and emotion. From Caravaggio\'s theatrical lighting to Rembrandt\'s golden glow, it is painting\'s most powerful tool.',
  'Texture': 'The visual and tactile quality of a surface. From Van Gogh\'s thick impasto to smooth glazing, texture adds a physical dimension to visual art that engages both eye and imagination.',
  'Form': 'The three-dimensional quality of objects in art — how shape, volume, and mass create presence. Form transforms flat marks into objects that seem to occupy real space.',
  'Movement': 'The suggestion of motion and energy in static art. From Duchamp\'s descending nude to Futurism\'s speed lines, capturing movement challenges art to transcend its own stillness.',
  'Balance': 'The distribution of visual weight in a composition. Symmetrical or asymmetrical, balance creates harmony or tension, stability or dynamism — the foundation of visual order.',
  'Contrast': 'The juxtaposition of opposing elements — light/dark, rough/smooth, large/small. Contrast creates visual interest, directs attention, and generates the energy that makes art compelling.',
  'Harmony': 'The pleasing arrangement of parts into a coherent whole. In visual art, harmony emerges from consistent use of color, form, and rhythm — creating unity without monotony.',
  'Symbolism': 'The use of images, objects, and forms to represent ideas beyond their literal meaning. From religious iconography to modern semiotics, symbolism is how art communicates the invisible.',
  'Abstract Expression': 'Art that communicates through pure form, color, and gesture rather than representation. Pioneered by Kandinsky, perfected by Pollock and Rothko, it seeks direct emotional and spiritual expression.',
  'Realism': 'The faithful representation of the visible world. From Courbet\'s radical insistence on depicting ordinary life to photorealism, it asks: what does it mean to truly see?',
  'Surrealism': 'Art that explores the unconscious mind, dreams, and irrational juxtaposition. Founded by Breton, realized by Dalí and Magritte, it reveals the strange logic beneath rational surfaces.',
  'Minimalism': 'The reduction of art to its essential elements. "Less is more." From Malevich\'s Black Square to Judd\'s boxes, minimalism strips away everything non-essential to reveal pure presence.',

  // History
  'Cultural Evolution': 'How ideas, beliefs, technologies, and practices change and spread across societies over time. Unlike biological evolution, cultural evolution is Lamarckian — acquired traits can be passed on.',
  'Social Movements': 'Collective efforts to bring about social change — from abolition to suffrage to civil rights to environmentalism. They reveal how ordinary people, organized, can reshape the world.',
  'Power Structures': 'The systems — political, economic, social — through which authority is exercised and maintained. Understanding power structures reveals who decides, who benefits, and who is marginalized.',
  'Revolution': 'The rapid, fundamental transformation of political or social order. From the French Revolution to the Arab Spring, revolutions are history\'s most dramatic moments of rupture and renewal.',
  'Democracy': 'Government by the people. Born in Athens, evolved through centuries, still contested today. Democracy is both a set of institutions and an ideal — the ongoing experiment of collective self-governance.',
  'Civilization': 'The complex social organization that emerges when humans settle, specialize, and build. Writing, cities, laws, art — civilization is humanity\'s grandest collective project.',
  'Trade Routes': 'The arteries of cultural exchange — the Silk Road, maritime spice routes, trans-Saharan trade. Along with goods, they carried ideas, religions, technologies, and diseases that shaped the world.',
  'Diplomacy': 'The art of negotiation between nations. From ancient treaty-making to modern international institutions, diplomacy is how humanity attempts to resolve conflicts without violence.',
  'Warfare': 'Organized armed conflict between groups. While destructive, warfare has been a primary driver of technological innovation, political change, and the formation of states throughout history.',
  'Renaissance': 'The "rebirth" of classical learning in 14th-17th century Europe. It produced Leonardo, Michelangelo, Shakespeare, and Galileo — and transformed art, science, and the very concept of the individual.',
  'Enlightenment': 'The 18th-century intellectual movement championing reason, science, and individual rights. It gave us democracy, human rights, and the scientific method — the intellectual foundation of the modern world.',
  'Industrial Revolution': 'The transformation from agrarian to industrial economies, beginning in 18th-century Britain. Steam power, factories, and railways reshaped not just economies but the entire human relationship with time, space, and nature.',
  'Globalization': 'The increasing interconnection of the world\'s economies, cultures, and populations. Accelerated by technology and trade, it creates both unprecedented opportunities and profound challenges of inequality and identity.',
  'Colonialism': 'The practice of establishing control over foreign peoples and territories. Its legacy — economic exploitation, cultural destruction, and institutional racism — continues to shape the modern world.',
  'Human Rights': 'The idea that all people possess inherent dignity and fundamental freedoms. From the Magna Carta to the Universal Declaration, human rights represent humanity\'s aspirational moral framework.'
};
