// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qsqfdzbyuxwgfgeprsgb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFzcWZkemJ5dXh3Z2ZnZXByc2diIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NDI0NTEsImV4cCI6MjA2NTUxODQ1MX0.GwATP8I-L-cOt3lnL-AhV-AxsiXMUOhVYKs-Yp0klrI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);